apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-learning-app
  namespace: argocd
  labels:
    app.kubernetes.io/name: k8s-learning-app
    app.kubernetes.io/part-of: kubernetes-concepts-demo
spec:
  project: default
  source:
    repoURL: https://github.com/ajayverse404/cncf-playground.git
    targetRevision: HEAD
    path: infra
    kustomize:
      commonLabels:
        app.kubernetes.io/managed-by: argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: k8s-learning
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

