apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: k8s-learning
  labels:
    app: frontend
    app.kubernetes.io/part-of: kubernetes-concepts-demo
data:
  config.json: |
    {
      "apiBaseUrl": "http://backend-service.k8s-learning.svc.cluster.local:8000"
    }

